#!/bin/bash

# Defaults, if not overridden by the environment.
if [ -z "$congress" ]; then
    congress=114
fi

if [ -z "$session" ]; then
    session=2015
fi
echo Congress: $congress Session: $session



function usage () {
    program=$(readlink -f "$0")
    program=$(basename "$program")
    echo "USAGE: $program <complete|daily|hourly>"
    exit 1
}


function which_guard () {
    w=$(which "$1")
    if [ -z "$w" ]; then
        echo "You must install $1."
        exit 2
    fi
}

function pid_file_guard () {
    script=$(basename $(readlink -f "$0"))
    pidfile="$HOME/tmp/${script}.pid"
    if [ -f "$pidfile" ]; then
        echo >&2 "Aborting ($mode mode) because another instance of this script is already running. Check $pidfile"
        exit 1
    fi
    trap "rm -f $pidfile" EXIT
    echo $$ > $pidfile
}

function show_pstree () {
    pstree --arguments --compact $$
}


which_guard "ssed"
which_guard "pstree"

if [ "$#" -eq 1 ]; then
    [ "$1" == "complete" ] && mode="$1"
    [ "$1" == "daily" ] && mode="$1"
    [ "$1" == "hourly" ] && mode="$1"
fi

[ -z "$mode" ] && usage

pid_file_guard

bills_args="--patch=opencongress --timeout=60 --congress=$congress --force --log=info"
amendments_args="--patch=opencongress --timeout=60 --congress=$congress --force --log=info"
votes_args="--patch=opencongress --timeout=60 --congress=$congress --session=$session --force --log=info"
if [ "$mode" == "hourly" ]; then
    bills_args="$bills_args --fast"
    amendments_args="$amendments_args --fast"
    votes_args="$votes_args --fast"
fi
# Scrape bills and amendments sequentially to avoid having amendment files
# that reference bills which we have not yet scraped.
( ./run bills $bills_args \
      2>&1 >> $HOME/log/bills.log &&
  ./run amendments $amendments_args \
      2>&1 >> $HOME/log/amendments.log ) &

( ./run votes $votes_args \
      2>&1 >> $HOME/log/votes.log ) &


if [ "$mode" == "complete" -o "$mode" == "daily" ]; then
    # The committee_meetings scraper does not have a fast mode. Don't run it too often.
    ( ./run committee_meetings --congress=$congress --log=info \
          2>&1 | tee -a $HOME/log/committee_meetings.log > $HOME/tmp/committee_meetings.last &&
      touch $HOME/tmp/committee_meetings.updated ) &

    ( ./run fdsys --collections=CRPT --store=mods --log=info \
          2>&1 | tee -a $HOME/log/fdsys_crpt.log > $HOME/tmp/fdsys_crpt.last &&
      touch $HOME/tmp/fdsys_crpt.updated ) &
fi

sleep 1
show_pstree

echo "Wait for all scrapers to finish..."
trap "show_pstree" SIGCHLD
wait




